function M_bar = Five_Bar_Mass_Matrix(t,in2,in3,in4,in5,g)
%FIVE_BAR_MASS_MATRIX
%    M_BAR = FIVE_BAR_MASS_MATRIX(T,IN2,IN3,IN4,IN5,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    08-May-2019 22:55:31

l1 = in5(1,:);
l2 = in5(2,:);
l3 = in5(3,:);
l4 = in5(4,:);
m1 = in4(1,:);
m2 = in4(2,:);
m3 = in4(3,:);
m4 = in4(4,:);
q1 = in2(1,:);
q2 = in2(2,:);
q4 = in2(4,:);
q5 = in2(3,:);
t2 = l1.^2;
t3 = cos(q2);
t4 = q1+q2;
t5 = l1.*t3;
t6 = l2+t5;
t7 = l2.*m2.*t6;
t8 = l2.^2;
t9 = m2.*t8;
t10 = sin(t4);
t11 = cos(t4);
t12 = l2.*t11;
t13 = l4.^2;
t14 = cos(q4);
t15 = q4+q5;
t16 = l4.*t14;
t17 = l3+t16;
t18 = l3.*m3.*t17;
t19 = l3.^2;
t20 = m3.*t19;
t21 = sin(t15);
t22 = l3.*t21;
t23 = cos(t15);
t24 = sin(q1);
t26 = l2.*t10;
t25 = -t26-l1.*t24;
t27 = sin(q5);
t28 = l4.*t27;
t29 = t22+t28;
t30 = cos(q1);
t31 = l1.*t30;
t32 = t12+t31;
t33 = cos(q5);
t35 = l3.*t23;
t34 = -t35-l4.*t33;
M_bar = reshape([t9+m1.*t2+m2.*t2+l1.*l2.*m2.*t3.*2.0,t7,0.0,0.0,t25,t32,t7,t9,0.0,0.0,-t26,t12,0.0,0.0,t20+m3.*t13+m4.*t13+l3.*l4.*m3.*t14.*2.0,t18,t29,t34,0.0,0.0,t18,t20,t22,-t35,t25,-l2.*t10,t29,t22,0.0,0.0,t32,t12,t34,-l3.*t23,0.0,0.0],[6,6]);
