function D_bar = Five_Bar_CN_Matrix(t,in2,in3,in4,in5,g)
%FIVE_BAR_CN_MATRIX
%    D_BAR = FIVE_BAR_CN_MATRIX(T,IN2,IN3,IN4,IN5,G)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    09-May-2019 09:43:00

dq1 = in2(5,:);
dq2 = in2(6,:);
dq4 = in2(8,:);
dq5 = in2(7,:);
l1 = in5(1,:);
l2 = in5(2,:);
l3 = in5(3,:);
l4 = in5(4,:);
m1 = in4(1,:);
m2 = in4(2,:);
m3 = in4(3,:);
m4 = in4(4,:);
q1 = in2(1,:);
q2 = in2(2,:);
q4 = in2(4,:);
q5 = in2(3,:);
tau1 = in3(1,:);
tau2 = in3(2,:);
tau4 = in3(4,:);
tau5 = in3(3,:);
t2 = cos(q1);
t3 = sin(q2);
t4 = q1+q2;
t5 = cos(t4);
t6 = cos(q5);
t7 = sin(q4);
t8 = q4+q5;
t9 = cos(t8);
t10 = dq1+dq2;
t11 = dq4+dq5;
t12 = sin(t4);
t13 = sin(t8);
D_bar = [tau1-g.*m2.*(l1.*t2+l2.*t5)-g.*l1.*m1.*t2+dq1.*dq2.*l1.*l2.*m2.*t3+dq2.*l1.*l2.*m2.*t3.*t10;tau2-g.*l2.*m2.*t5-dq1.^2.*l1.*l2.*m2.*t3;tau5-g.*m3.*(l4.*t6+l3.*t9)-g.*l4.*m4.*t6+dq4.*dq5.*l3.*l4.*m3.*t7+dq4.*l3.*l4.*m3.*t7.*t11;tau4-g.*l3.*m3.*t9-dq5.^2.*l3.*l4.*m3.*t7;dq1.*(dq1.*l1.*t2+dq1.*l2.*t5+dq2.*l2.*t5)-dq5.*(dq5.*l4.*t6+dq4.*l3.*t9+dq5.*l3.*t9)+dq2.*l2.*t5.*t10-dq4.*l3.*t9.*t11;dq1.*(dq1.*l1.*sin(q1)+dq1.*l2.*t12+dq2.*l2.*t12)-dq5.*(dq5.*l4.*sin(q5)+dq4.*l3.*t13+dq5.*l3.*t13)+dq2.*l2.*t10.*t12-dq4.*l3.*t11.*t13];
