function P3 = fk(a_1,a_2,a_3,a_4,a_5,t_1,t_5)
%FK
%    P3 = FK(A_1,A_2,A_3,A_4,A_5,T_1,T_5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    22-Jan-2019 16:23:28

t6 = sin(t_1);
t7 = a_1.*t6;
t8 = sin(t_5);
t9 = a_4.*t8;
t10 = t7-t9;
t2 = abs(t10);
t3 = cos(t_1);
t4 = a_1.*t3;
t12 = cos(t_5);
t13 = a_4.*t12;
t14 = a_5+t4-t13;
t5 = abs(t14);
t11 = t2.^2;
t15 = t5.^2;
t16 = t11+t15;
t18 = a_2.^2;
t20 = a_3.^2;
t17 = t11+t15-t18+t20;
t19 = 1.0./t16;
t21 = 1.0./sqrt(t16);
t22 = t17.^2;
t23 = t18-t19.*t22.*(1.0./4.0);
t24 = sqrt(t23);
P3 = [t4-t14.*t17.*t19.*(1.0./2.0)-t10.*t21.*t24;t7-t10.*t17.*t19.*(1.0./2.0)+t14.*t21.*t24];
